var testArray = [
{ service: "cartesius", resource: "Metadata"},
{ service: "northwind", resource: "Metadata"},
{ service: "northwind", resource: "employees", filter: "EmployeeID eq 1"},
{ service: "northwind", resource: "orders", filter: "Freight gt 100"},
{ service: "northwind", resource: "orders", filter: "OrderDate ge datetime'1998-04-28T17:00:00.000Z'"},
{ service: "northwind", resource: "employees", filter: "Region ne null"},
{ service: "northwind", resource: "suppliers", filter: "(City eq 'London') or (City eq 'Paris')"},
{ service: "northwind", resource: "orders", filter: "(Freight gt 100) and (OrderDate gt datetime'1998-03-31T17:00:00.000Z')"},
{ service: "northwind", resource: "orders", filter: "(Freight gt 100) or (OrderDate gt datetime'1998-03-31T17:00:00.000Z')"},
{ service: "northwind", resource: "orders", filter: "((OrderDate ge datetime'1995-12-31T17:00:00.000Z') and (OrderDate lt datetime'1996-12-31T17:00:00.000Z')) and (Freight gt 100)"},
{ service: "northwind", resource: "suppliers", filter: "length(CompanyName) gt 30"},
{ service: "northwind", resource: "suppliers", filter: "toupper(substring(CompanyName,1,2)) eq 'OM'"},
{ service: "northwind", resource: "suppliers", filter: "substringof('market',CompanyName) eq true"},
{ service: "northwind", resource: "products", filter: "startswith(ProductName,'C') eq true"},
{ service: "northwind", resource: "orders", filter: "not (Freight gt 100)"},
{ service: "northwind", resource: "products", expand: "Suppliers"},
{ service: "northwind", resource: "suppliers", filter: "(startswith(CompanyName,'S') eq true) and (substringof('er', City) eq true)"},
{ service: "cartesius", resource: "account", filter: "id eq 2", expand: "ProjectAuthor"},
{ service: "northwind", resource: "products", filter: "startswith(Categories/CategoryName,'C') eq true", select: "ProductName,Categories/CategoryName"},
{ service: "cartesius", resource: "project", filter: "id eq 2", select: "title, ProjectAuthor/Account"},
{ service: "northwind", resource: "orders", filter: "Customers/Region eq 'CA'"},
{ service: "northwind", resource: "products", filter: "startswith(Suppliers/CompanyName,'S') eq true", orderby: "UnitPrice desc,ProductName"},
{ service: "northwind", resource: "products", filter: "startswith(Suppliers/CompanyName,'S') eq true", orderby: "Suppliers/CompanyName"},
{ service: "northwind", resource: "products", filter: "startswith(Suppliers/CompanyName,'S') eq true", orderby: "Suppliers/CompanyName"},
{ service: "northwind", resource: "customers", filter: "(startswith(CompanyName,'S')eq true) and (substringof('er',City) eq true)", select: "CompanyName,City"},
{ service: "northwind", resource: "employees", select: "Photo", filter: "Region ne null"}];
